# WARNING - Generated by {fusen} from dev/flat_get_info_data.Rmd: do not edit by hand

test_that("on a bien une erreur si df n'est pas un dataframe", {
  expect_error(
    object = get_info_data(df = 3),
    regexp = "L'objet fourni n'est pas un data frame"
  )})

  test_that("la sortie de la fonction est bien une liste", {resultats <- get_info_data(iris)
   expect_true(is.list(resultats), info = "La sortie n'est pas une liste")
  })
      

  test_that("la sortie de la fonction est bien une liste de deux éléments", {
    resultats <- get_info_data(iris)
    expect_equal(length(resultats), 2, info = "La liste ne contient pas deux éléments")
})

