# WARNING - Generated by {fusen} from dev/flat_get_mean_data.Rmd: do not edit by hand

test_that("Test avec un data frame contenant des variables numeriques et non numeriques", {
  data_test <- data.frame(a = 1:3, b = c("x", "y", "z"), c = 4:6)
  result <- get_mean_data(data_test)
  expect_equal(result$a, mean(1:3))
  expect_equal(result$c, mean(4:6))
})

test_that("Test avec un data frame ne contenant que des variables non numeriques", {
  data_test <- data.frame(a = c("x", "y", "z"), b = c("foo", "bar", "baz"))
  expect_message(get_mean_data(data_test), "Le jeu de donnees ne comporte pas de variables numeriques")
})



test_that("Test avec un data frame contenant des valeurs NA", {
  data_test <- data.frame(a = c(1, 2, NA), b = c(4, 5, 6))
  result <- get_mean_data(data_test)
  expect_equal(result$a, mean(c(1, 2), na.rm = TRUE))
  expect_equal(result$b, mean(c(4, 5, 6), na.rm = TRUE))
})

test_that("Test avec un objet qui n'est pas un data frame", {
  data_test <- list(a = 1:3, b = 4:6)
  expect_error(get_mean_data(data_test), "L'objet fourni n'est pas un data frame")
})

test_that("Test avec un data frame contenant des variables numeriques avec des moyennes connues", {
  data_test <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6))
  result <- get_mean_data(data_test)
  expect_equal(result$a, 2)
  expect_equal(result$b, 5)
})

