# WARNING - Generated by {fusen} from dev/flat_get_info_data.Rmd: do not edit by hand

#' flat_get_info_data Title
#'
#'créer une fonction qui permettra d’avoir des informations sur un jeu de données passé en paramètre : dimensions et nom des colonnes dans une liste
#' @return list
#' @param mydata dataframe
#' 
#' @export
#'
#' @examples
#' get_info_data(iris)
#' get_info_data(dplyr::starwars)
get_info_data <- function(mydata) {

  if (!is.data.frame(mydata)) {
    stop("mydata is not a data frame")
  }
  
  dimensions <- dim(mydata)
  names <- colnames(mydata)
  informations <- list(dimensions = dimensions, names = names)

  return(informations)
}

