# WARNING - Generated by {fusen} from dev/flat_get_info_data.Rmd: do not edit by hand

#' flat_get_info_data Title
#'
#'créer une fonction qui permettra d’avoir des informations sur un jeu de données passé en paramètre : dimensions et nom des colonnes dans une liste
#' @return list
#' @param df dataframe
#' 
#' @export
#'
#' @examples
#' get_info_data(iris)
#' get_info_data(dplyr::starwars)
get_info_data <- function(df) {

  if (!is.data.frame(df)) {
    stop("L'objet fourni n'est pas un data frame")
  }
  
  dimensions <- dim(df)
  names <- colnames(df)
  informations <- list(dimensions = dimensions, names = names)

  return(informations)
}

