# WARNING - Generated by {fusen} from dev/flat_get_mean_data.Rmd: do not edit by hand

#' get_mean_data Title
#' Permet d'obtenir la moyenne de toutes les colonnes numeriques
#' @return 1
#'
#' @param mydata dataframe
#'
#' @export
#' @importFrom dplyr across 
#' @importFrom dplyr summarize
#' @importFrom dplyr everything
#' @examples

#' get_mean_data(iris)
#'
get_mean_data <- function(mydata) {
  if (!is.data.frame(mydata)) {
    stop("L'objet fourni n'est pas un data frame")
  }
  
  data_numerique <- mydata[sapply(mydata, is.numeric)]
  if (ncol(data_numerique) == 0) {
    message("Le jeu de donnees ne comporte pas de variables numeriques")
  }
 
means <-data_numerique |> 
    summarize(across(
      everything(),
      \(x) mean(x, na.rm = TRUE)
      ) 
      )
  return(means)
}




